# Generated by Django 5.2.4 on 2025-07-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_cart_alter_order_status_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
